# -*- coding: utf-8 -*-
"""score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10CdtpHf2eLodZ8GV9rM8zYnEDAvB1qVs
"""

grades = input().split()

maxPeople = 0
minPeople = 100

for i in grades:
  if(int(i)>maxPeople):maxPeople = int(i)
  elif(int(i)<minPeople):minPeople = int(i)
print(maxPeople, minPeople)

average = sum(int(grades)) / len(int(grades))

print(average)
