# -*- coding: utf-8 -*-
"""Score_Max_Min.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17A5urR0umCN6Vl1x7_lNZxSel-u3bvuB
"""

grades = input().split()

maxPeople = 0
minPeople = 100

for i in grades:
  if(int(i)>maxPeople):maxPeople = int(i)
  elif(int(i)<minPeople):minPeople = int(i)
print(maxPeople, minPeople)